//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRY.QQ.Simulate.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRY.QQ.Simulate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   function getCSRFToken(skey) {
        ///                var e = skey
        ///                  , n = 5381;
        ///                for (var r = 0, i = e.length; r &lt; i; ++r)
        ///                    n += (n &lt;&lt; 5) + e.charAt(r).charCodeAt();
        ///                return n &amp; 2147483647
        ///            }
        ///var Encryption = function() {
        ///    function t(t) {
        ///        return e(t)
        ///    }
        ///    function e(t) {
        ///        return u(i(c(t), t.length * m))
        ///    }
        ///    function i(t, e) {
        ///        t[e &gt;&gt; 5] |= 128 &lt;&lt; e % 32,
        ///        t[(e + 64 &gt;&gt;&gt; 9 &lt;&lt; 4) + 14] = e;
        ///        f [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string c_login_2 {
            get {
                return ResourceManager.GetString("c_login_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   var ArraryKey=[&quot;\x70\x61\x72\x73\x65&quot;,&quot;\x6D\x6F\x75\x73\x65\x6D\x6F\x76\x65&quot;,&quot;\x6D\x6F\x75\x73\x65\x63\x6C\x69\x63\x6B&quot;,&quot;\x6B\x65\x79\x76\x61\x6C\x75\x65&quot;,&quot;\x75\x73\x65\x72\x5F\x41\x67\x65\x6E\x74&quot;,&quot;\x72\x65\x73\x6F\x6C\x75\x74\x69\x6F\x6E\x78&quot;,&quot;\x72\x65\x73\x6F\x6C\x75\x74\x69\x6F\x6E\x79&quot;,&quot;\x75\x72\x6C&quot;,&quot;\x72\x65\x66\x65\x72&quot;,&quot;\x62\x65\x67\x69\x6E\x74\x69\x6D\x65&quot;,&quot;\x65\x6E\x64\x74\x69\x6D\x65&quot;,&quot;\x70\x6C\x61\x74\x66\x6F\x72\x6D&quot;,&quot;\x6F\x73&quot;,&quot;\x6B\x65\x79\x62\x6F\x61\x72\x64\x73&quot;,&quot;\x66\x6C\x61\x73\x68&quot;,&quot;\x7 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TDC {
            get {
                return ResourceManager.GetString("TDC", resourceCulture);
            }
        }
    }
}
